# fly.toml file generated for boatmate on 2023-03-30T16:42:20-04:00

app = "boatmate"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "mia"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
